# Weight Watcher Twitter Hashtags Trending in the US Within the Last 30 Days?

In [1]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import pprint
import tweepy
import geocoder
import gmaps

# Import Twitter API Keys
from twitter_api import api_key, api_key_secret, access_token, access_token_secret

# Initialize Tweepy
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

In [2]:
# Base URL for Collecting 30-Day Endpoint (API Data)

from requests_oauthlib import OAuth1

# Get Data About Trending Diet Trends on Twitter: Weight Watchers
url = "https://api.twitter.com/1.1/tweets/search/30day/DataAnalyticsProject.json"
auth = OAuth1(api_key, api_key_secret, access_token, access_token_secret)

# Weight Watchers API Requests
url_params = {'query': 'place_country:us #weightwatchers'}
r = requests.get(url, auth=auth, params=url_params)

In [3]:
# Set Up Lists to Hold Reponse Info
ww_location_list = []
ww_location_dict = {}

# Set Counter to 0
count = 0

# Loop Through Tweets & Perform a Request for Data on Each
for tweet in r.json()["results"]:
    
    try:
        # Get & Print Location of Tweets
        user_name = tweet["user"]["screen_name"]
        location = tweet["user"]["location"]
        tweet_location = tweet["place"]["full_name"]
        lat, lng = geocoder.arcgis(tweet_location).latlng
        print(f"The user, {user_name}, is located in {tweet_location}, {lat}, {lng}")

        # Build Dictionary
        ww_location_dict = {
             "user": user_name,
             "tweet_location": tweet_location,
             "lat": lat,
             "lng": lng
        }

        # Add Dictionary to List
        ww_location_list.append(ww_location_dict)
        
        # Increment Counter by 1
        count += 1
        
    except:
         continue

print(count)

# Create DataFrame
ww_location_df = pd.DataFrame(ww_location_list)
ww_location_df

The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, Heather_T_1972, is located in Liverpool, NY, 43.10424000000006, -76.20964999999995
The user, ClaireArnaudAub, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, fitness_mvp, is located in Hutto, TX, 30.543570000000045, -97.54292999999996
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, TheSkepticalV, is located in Cayuga Heights, NY, 42.47697000000005, -76.49902999999995
The user, DarrenRansdell, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, NYTheDietDiva, is located in Indian Harbour Beach, FL, 28.146030000000053, -80.59868999999998
The user, TracyCrockett80, is located in Wichita, KS, 37.68698000000006, -97.33557999999994
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, NYTheDietDiva, is located in Indian Harbour Beach, FL, 28.146030000000053, -80.59868999999998
The user, NYTheDietDiva, is located in Indian Harbour Beach, FL, 28.146030000000053, -80.59868999999998
The user, DwightAFerrell, is located in Weight Watchers, -31.895959999999945, 115.89795000000004
The user, NYTheDietDiva, is located in Indian Harbour Beach, FL, 28.146030000000053, -80.59868999999998
The user, JenEyePrince, is located in Duck Donuts, 40.077270000000055, -76.32673999999997
The user, DarrenRansdell, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, bodhach, is located in New York, USA, 40.71455000000003, -74.00713999999994
The user, JulieBear328, is located in Warwick, RI, 41.69897000000003, -71.46205999999995
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, iveymichele, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, JulieBear328, is located in Warwick, RI, 41.69897000000003, -71.46205999999995
The user, mpngirl, is located in West Freehold, NJ, 40.24544000000003, -74.29663999999997
The user, _invincible15_, is located in Ohio, USA, 40.41305679900006, -82.71121518599995
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, jenniferaleice, is located in Washington, DC, 38.890370000000075, -77.03195999999997
The user, PMSClinic, is located in Arcadia, CA, 34.13614000000007, -118.03886999999997
The user, BeeColvin, is located in Austin, TX, 30.26759000000004, -97.74298999999996
The user, doublecinc, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, StAmyPatrick, is located in Abingdon, MD, 39.463670000000036, -76.27845999999994
The user, DJHano, is located in Paramus, NJ, 40.926990000000046, -74.06128999999999
The user, OrleanCLapinid, is located in Ventura, CA, 34.28082000000006, -119.29231999999996
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, loss_my_weight, is located in New York, USA, 40.71455000000003, -74.00713999999994
The user, DivaAndDivine, is located in Des Plaines, IL, 42.042260000000056, -87.88910999999996
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, RusherAttack, is located in Natick, MA, 42.28400000000005, -71.34616999999997
The user, JulieBear328, is located in Warwick, RI, 41.69897000000003, -71.46205999999995
The user, JSODonoghue, is located in Bethesda, MD, 38.98637000000008, -77.09691999999995
The user, TBAH_Ryan, is located in Pennsylvania, USA, 40.89651165400005, -77.83875077599998
The user, shrinkingkristy, is located in Carmel, IN, 39.97839000000005, -86.12612999999999
The user, shrinkingkristy, is located in Carmel, IN, 39.97839000000005, -86.12612999999999
The user, shrinkingkristy, is located in Carmel, IN, 39.97839000000005, -86.12612999999999
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, GeneCaldwellSD, is located in San Diego, CA, 32.71568000000008, -117.16170999999997
The user, shrinkingkristy, is located in Carmel, IN, 39.97839000000005, -86.12612999999999
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, ketoweightlos, is located in United States, 39.39870315600007, -99.41461918999994
The user, weightlossrview, is located in United States, 39.39870315600007, -99.41461918999994
The user, SarasKithen_LV, is located in Paradise, NV, 36.09990000000005, -115.11501999999996
The user, mdsuburbs, is located in Glenn Dale, MD, 38.98748000000006, -76.81927999999994
The user, mpsmami, is located in South El Monte, CA, 34.046440000000075, -118.04325999999998
The user, mpsmami, is located in South El Monte, CA, 34.046440000000075, -118.04325999999998
The user, louiseshaney1, is located in Little Rock, AR, 34.74870000000004, -92.27484999999996
The user, amygreil, is located in North Attleboro, MA, 41.98133000000007, -71.33274999999998
The user, fitness_mvp, is located in Hutto, TX, 30.543570000000045, -97.54292999999996
The user, swhitson, is located in Texas, USA, 31.46273304600004, -99.33305008999997
The user, TicketToMagic, is located in New Braunfels, TX, 29.698870000000056, -98.12093999999996
The user, itsedwardoz, is located in Fort Lauderdale, FL, 26.123880000000042, -80.14356999999995
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, juliekellyroge1, is located in Denham Springs, LA, 30.48703000000006, -90.95544999999998
The user, lisabeatsmeat, is located in Columbus, OH, 39.96199000000007, -83.00274999999993
The user, sobobaweightlos, is located in Newport Beach, CA, 33.61703000000006, -117.93032999999997
The user, swhitson, is located in Texas, USA, 31.46273304600004, -99.33305008999997
The user, reader1718, is located in Hoover, AL, 33.38791000000003, -86.80602999999996
The user, SandyMueller2, is located in Illinois, USA, 40.11404657000003, -89.15865090199998
The user, MrSpargel, is located in Honolulu, HI, 21.30493000000007, -157.85787999999997
The user, the59thStBridge, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, jmiddlebrook, is located in Linganore, MD, 39.440330000000074, -77.20846999999998
The user, daytonnutrition, is located in Troy, OH, 40.04003000000006, -84.20421999999996
The user, mfanton, is located in Wellsville, NY, 42.12784000000005, -77.95913999999993
The user, Californiakone, is located in Clinton, MD, 38.76156000000003, -76.91459999999995
The user, GWhiteFitness, is located in Las Vegas, NV, 36.17193000000003, -115.14000999999996
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, whbutler2, is located in Cinco Ranch, TX, 29.73875000000004, -95.75788999999997
The user, daddynole, is located in Royal Palm Beach, FL, 26.705750000000023, -80.22916999999995
The user, DjBillLovelace, is located in Cypress, CA, 33.82434000000006, -118.03722999999997
The user, SarasKithen_LV, is located in Paradise, NV, 36.09990000000005, -115.11501999999996
The user, Skeet_79, is located in Denver, CO, 39.74001000000004, -104.99201999999997

The user, Skeet_79, is located in Denver, CO, 39.74001000000004, -104.99201999999997
The user, Heather_Created, is located in Virginia Beach, VA, 36.75528000000003, -76.05961999999994
The user, swhitson, is located in Georgetown, TX, 30.637910000000034, -97.67700999999994
The user, SarasKithen_LV, is located in Paradise, NV, 36.09990000000005, -115.11501999999996
The user, RadioChio, is located in Inglewood, CA, 33.96178000000003, -118.35673999999995
The user, stanleymwc, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, 94__MARKK, is located in Cerritos, CA, 33.86854000000005, -118.06369999999998
The user, swhitson, is located in Round Rock, TX, 30.509040000000027, -97.67721999999998
98

          lat         lng            tweet_location             user
0   39.398703  -99.414619             United States  weightlossrview
1   43.104240  -76.209650             Liverpool, NY   Heather_T_1972
2   34.053490 -118.245320           Los Angeles, CA  ClaireArnaudAub
3   30.543570  -97.542930                 Hutto, TX      fitness_mvp
4   30.637910  -97.677010            Georgetown, TX         swhitson
5   42.476970  -76.499030        Cayuga Heights, NY    TheSkepticalV
6   34.053490 -118.245320           Los Angeles, CA   DarrenRansdell
7   28.146030  -80.598690  Indian Harbour Beach, FL    NYTheDietDiva
8   37.686980  -97.335580               Wichita, KS  TracyCrockett80
9   30.637910  -97.677010            Georgetown, TX         swhitson
10  28.146030  -80.598690  Indian Harbour Beach, FL    NYTheDietDiva
11  28.146030  -80.598690  Indian Harbour Beach, FL    NYTheDietDiva
12 -31.895960  115.897950           Weight Watchers   DwightAFerrell
13  28.146030  -80.598690  Indian Harbour Beach, FL    NYTheDietDiva
14  40.077270  -76.326740               Duck Donuts     JenEyePrince
15  34.053490 -118.245320           Los Angeles, CA   DarrenRansdell
16  40.714550  -74.007140             New York, USA          bodhach
17  41.698970  -71.462060               Warwick, RI     JulieBear328
18  39.398703  -99.414619             United States    ketoweightlos
19  39.398703  -99.414619             United States  weightlossrview
20  39.398703  -99.414619             United States  weightlossrview
21  39.398703  -99.414619             United States    ketoweightlos
22  40.714500  -74.006010             Manhattan, NY      iveymichele
23  41.698970  -71.462060               Warwick, RI     JulieBear328
24  40.245440  -74.296640         West Freehold, NJ          mpngirl
25  40.413057  -82.711215                 Ohio, USA   _invincible15_
26  39.398703  -99.414619             United States    ketoweightlos
27  39.398703  -99.414619             United States  weightlossrview
28  38.890370  -77.031960            Washington, DC   jenniferaleice
29  34.136140 -118.038870               Arcadia, CA        PMSClinic
..        ...         ...                       ...              ...
68  39.961990  -83.002750              Columbus, OH    lisabeatsmeat
69  33.617030 -117.930330         Newport Beach, CA  sobobaweightlos
70  31.462733  -99.333050                Texas, USA         swhitson
71  33.387910  -86.806030                Hoover, AL       reader1718
72  40.114047  -89.158651             Illinois, USA    SandyMueller2
73  21.304930 -157.857880              Honolulu, HI        MrSpargel
74  40.692450  -73.990360              Brooklyn, NY  the59thStBridge
75  39.440330  -77.208470             Linganore, MD     jmiddlebrook
76  40.040030  -84.204220                  Troy, OH  daytonnutrition
77  42.127840  -77.959140            Wellsville, NY          mfanton
78  38.761560  -76.914600               Clinton, MD   Californiakone
79  36.171930 -115.140010             Las Vegas, NV    GWhiteFitness
80  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
81  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
82  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
83  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
84  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
85  29.738750  -95.757890           Cinco Ranch, TX        whbutler2
86  26.705750  -80.229170      Royal Palm Beach, FL        daddynole
87  33.824340 -118.037230               Cypress, CA   DjBillLovelace
88  36.099900 -115.115020              Paradise, NV   SarasKithen_LV
89  39.740010 -104.992020                Denver, CO         Skeet_79
90  39.740010 -104.992020                Denver, CO         Skeet_79
91  36.755280  -76.059620        Virginia Beach, VA  Heather_Created
92  30.637910  -97.677010            Georgetown, TX         swhitson
93  36.099900 -115.115020              Paradise, NV   SarasKithen_LV
94  33.961780 -118.356740             Inglewood, CA        RadioChio
95  40.714500  -74.006010             Manhattan, NY       stanleymwc
96  33.868540 -118.063700              Cerritos, CA        94__MARKK
97  30.509040  -97.677220            Round Rock, TX         swhitson

[98 rows x 4 columns]

In [4]:
# Drop NaN's
ww_data_split_no_missing = ww_location_df.dropna()
ww_data_split_no_missing.head()

         lat         lng   tweet_location             user
0  39.398703  -99.414619    United States  weightlossrview
1  43.104240  -76.209650    Liverpool, NY   Heather_T_1972
2  34.053490 -118.245320  Los Angeles, CA  ClaireArnaudAub
3  30.543570  -97.542930        Hutto, TX      fitness_mvp
4  30.637910  -97.677010   Georgetown, TX         swhitson

In [5]:
# Create Open Columns
ww_data_split_no_missing["state"] = ""
ww_data_split_no_missing["city"] = ""
ww_data_split_no_missing

# Split City & State
ww_data_split_no_missing[["city", "state"]] = ww_data_split_no_missing["tweet_location"].str.split(",", expand=True)
ww_data_split_no_missing.head()

,lat,lng,tweet_location,user,state,city
0,39.398703,-99.414619,United States,weightlossrview,None,United States
1,43.104240,-76.209650,"Liverpool, NY",Heather_T_1972,NY,Liverpool
2,34.053490,-118.245320,"Los Angeles, CA",ClaireArnaudAub,CA,Los Angeles
3,30.543570,-97.542930,"Hutto, TX",fitness_mvp,TX,Hutto
4,30.637910,-97.677010,"Georgetown, TX",swhitson,TX,Georgetown

In [6]:
# Groupby "state" & Get Mean (Average) Location from Each state
locations = ww_data_split_no_missing.groupby("state").mean()
locations.head()

            lat         lng
state
 AL    33.38791  -86.806030
 AR    34.74870  -92.274850
 CA    33.88814 -118.141948
 CO    39.74001 -104.992020
 DC    38.89037  -77.031960

In [7]:
# Value Count Each "state" (Total Tweets per State) & Sort Index by Alphabetical Order to Align with Locations
location_counts = ww_data_split_no_missing["state"].value_counts()
reorganized_location_count = location_counts.sort_index()
reorganized_location_count

 AL      1
 AR      1
 CA     12
 CO      2
 DC      1
 FL      6
 HI      1
 IL      2
 IN      4
 KS      1
 LA      1
 MA      2
 MD      5
 NJ      2
 NV      4
 NY      6
 OH      2
 RI      3
 TX     19
 USA     7
 VA      1
Name: state, dtype: int64

In [8]:
# Plot Heatmap
fig = gmaps.figure()

# Create Heat Layer
heat_layer = gmaps.heatmap_layer(locations, weights=reorganized_location_count, dissipating=False, max_intensity=10, point_radius=1)

# Add Layer 
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))