# Whole30 Twitter Hashtags Trending in the US Within the Last 30 Days?

In [1]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import pprint
import tweepy
import geocoder
import gmaps

# Import Twitter API Keys
from twitter_api import api_key, api_key_secret, access_token, access_token_secret

# Initialize Tweepy
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

In [2]:
# Base URL for Collecting 30-Day Endpoint (API Data)

from requests_oauthlib import OAuth1

# Get Data About Trending Diet Trends on Twitter: Whole30
url = "https://api.twitter.com/1.1/tweets/search/30day/DataAnalyticsProject.json"
auth = OAuth1(api_key, api_key_secret, access_token, access_token_secret)

# Whole30 API Requests
url_params = {'query': 'place_country:us #whole30'}
r = requests.get(url, auth=auth, params=url_params)

In [3]:
# Set Up Lists to Hold Reponse Info
whole30_location_list = []
whole30_location_dict = {}

# Set Counter to 0
count = 0

# Loop Through Tweets & Perform a Request for Data on Each
for tweet in r.json()["results"]:
    
    try:
        # Get & Print Location of Tweets
        user_name = tweet["user"]["screen_name"]
        location = tweet["user"]["location"]
        tweet_location = tweet["place"]["full_name"]
        lat, lng = geocoder.arcgis(tweet_location).latlng
        print(f"The user, {user_name}, is located in {tweet_location}, {lat}, {lng}")

        # Build Dictionary
        whole30_location_dict = {
             "user": user_name,
             "tweet_location": tweet_location,
             "lat": lat,
             "lng": lng
        }

        # Add Dictionary to List
        whole30_location_list.append(whole30_location_dict)
        
        # Increment Counter by 1
        count += 1
        
    except:
         continue

print(count)

# Create DataFrame
whole30_location_df = pd.DataFrame(whole30_location_list)
whole30_location_df

The user, mtheodoreb, is located in South Ogden, UT, 41.191850000000045, -111.96757999999994
The user, soverycleveland, is located in Mabel's BBQ, 39.963770030007346, -75.59539997778293
The user, CatchGifUCan, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, rebekahljohnson, is located in Broomfield, CO, 39.92086000000006, -105.07057999999995
The user, FoxandBones, is located in Portland, OR, 45.511790000000076, -122.67562999999996
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, adinalav, is located in Editors Park, 6.98613000000006, 80.81386000000003
The user, BeingZhenya, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, ohsillyjo, is located in San Diego, CA, 32.71568000000008, -117.16170999999997
The user, Anastasia71, is located in Westwood, NJ, 40.99207000000007, -74.03597999999994
The user, Anastasia71, is located in Westwood, NJ, 40.99207000000007, -74.03597999999994
The user, JennaKDay, is located in Urbandale, IA, 41.625050000000044, -93.71242999999998
The user, Lizabelllaa, is located in Macedonia, OH, 41.313780000000065, -81.50464999999997
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, BrittanyJLadd, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, loubiesandlulu, is located in Richardson, TX, 32.960740000000044, -96.73296999999997
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, jpar0, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, Kadamo, is located in Warwick, RI, 41.69897000000003, -71.46205999999995
The user, carriedod, is located in Nashville, TN, 36.16784000000007, -86.77815999999996
The user, CA_Young, is located in Missouri, USA, 38.36798274600005, -92.47774661699998
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, RMBouton, is located in Queens, NY, 40.714000000000055, -73.82998999999995
The user, Steph_Demco, is located in Austin, TX, 30.26759000000004, -97.74298999999996
The user, kellyFreckles, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, adinalav, is located in Editors Park, 6.98613000000006, 80.81386000000003
The user, techybecky50, is located in Virginia, USA, 37.51282050400005, -78.69794871299996
The user, nicolestipp, is located in Louisville, KY, 38.254890000000046, -85.76665999999994
The user, MandiHefflinger, is located in Los Angeles, CA, 34.05349000000007, -118.24531999999999
The user, Anastasia71, is located in Westwood, NJ, 40.99207000000007, -74.03597999999994
The user, BrittanyJLadd, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, catherinegilb09, is located in St Louis, MO, 38.62775000000005, -90.19955999999996
The user, CapitalChiroDSM, is located in Des Moines, IA, 41.58981000000006, -93.61537999999996
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, thekitchendoor, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, ThugDebugger, is located in Atlanta, GA, 33.74831000000006, -84.39110999999997
The user, jerykahbaduisms, is located in San Jose, CA, 37.33865000000003, -121.88541999999995
The user, deiser11, is located in Aiken, SC, 33.56164000000007, -81.72213999999997
The user, CrispNoPo, is located in Portland, OR, 45.511790000000076, -122.67562999999996
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, enjoykombuchade, is located in Chicago, IL, 41.884250000000065, -87.63244999999995
The user, annalea, is located in Albuquerque, NM, 35.08423000000005, -106.64904999999999
The user, ThugDebugger, is located in Atlanta, GA, 33.74831000000006, -84.39110999999997
The user, enjoykombuchade, is located in Austin, TX, 30.26759000000004, -97.74298999999996
The user, caitlin_brimmer, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, danica_blanca, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, SprocketPodcast, is located in Portland, OR, 45.511790000000076, -122.67562999999996
The user, eemialove, is located in Algonquin, IL, 42.164390000000026, -88.32718999999997
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, Lyfestyle_Cater, is located in Olympia Heights, FL, 25.72685000000007, -80.35503999999997
The user, eemialove, is located in Huntley, IL, 42.16868000000005, -88.42569999999995
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, PaddyoII, is located in Atlanta, GA, 33.74831000000006, -84.39110999999997
The user, PaddyoII, is located in Atlanta, GA, 33.74831000000006, -84.39110999999997
The user, MissMelodyyy, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, budget_momma, is located in Long Beach, CA, 33.76672000000008, -118.19239999999996
The user, SeanPBlanchard, is located in Longmont, CO, 40.163940000000025, -105.10021999999998
The user, melissafreyauth, is located in Grand Blanc, MI, 42.927490000000034, -83.63015999999999
The user, SeanPBlanchard, is located in Longmont, CO, 40.163940000000025, -105.10021999999998
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, deboone, is located in Charlotte, NC, 35.222860000000026, -80.83795999999995
The user, HealthNutsStore, is located in Gulfport, MS, 30.38032000000004, -89.09188999999998
The user, Lyfestyle_Cater, is located in Olympia Heights, FL, 25.72685000000007, -80.35503999999997
The user, kellyFreckles, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, jingjingtaco, is located in Tampa, FL, 27.946530000000052, -82.45926999999995
The user, CrispNoPo, is located in Portland, OR, 45.511790000000076, -122.67562999999996
The user, OOHS_APYoung, is located in Columbus, OH, 39.96199000000007, -83.00274999999993
The user, kels_boyette, is located in Virginia Beach, VA, 36.75528000000003, -76.05961999999994
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, JoshRotter, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, JoshRotter, is located in San Francisco, CA, 37.777120000000025, -122.41963999999996
The user, Maneesha_J, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, caitlin_brimmer, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, SHUTUPRUSH, is located in St Paul, MN, 44.94339000000008, -93.09647999999999
The user, donachai, is located in Brooklyn, NY, 40.692450000000065, -73.99035999999995
The user, TheBGates, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, DancesWithRain, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, kimmfoote, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, kimmfoote, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
The user, loubiesandlulu, is located in Dallas, TX, 32.77815000000004, -96.79539999999997
The user, Robin_Tucker, is located in Tommy Tucker Realty, 52.21520000000004, 0.12554000000005772
The user, Lyfestyle_Cater, is located in Olympia Heights, FL, 25.72685000000007, -80.35503999999997
The user, dj_lizkhalifa, is located in Frederick, MD, 39.41574000000003, -77.41202999999996
The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998

The user, arthuradesign, is located in Kansas City, MO, 39.103440000000035, -94.58310999999998
The user, Anastasia71, is located in Westwood, NJ, 40.99207000000007, -74.03597999999994
The user, Anastasia71, is located in Westwood, NJ, 40.99207000000007, -74.03597999999994
The user, kels_boyette, is located in Virginia Beach, VA, 36.75528000000003, -76.05961999999994
The user, Dsummer, is located in Seattle, WA, 47.60357000000005, -122.32944999999995
The user, TheBGates, is located in Manhattan, NY, 40.714500000000044, -74.00600999999995
96

          lat         lng       tweet_location             user
0   41.191850 -111.967580      South Ogden, UT       mtheodoreb
1   39.963770  -75.595400          Mabel's BBQ  soverycleveland
2   40.692450  -73.990360         Brooklyn, NY     CatchGifUCan
3   39.920860 -105.070580       Broomfield, CO  rebekahljohnson
4   45.511790 -122.675630         Portland, OR      FoxandBones
5   39.103440  -94.583110      Kansas City, MO    arthuradesign
6    6.986130   80.813860         Editors Park         adinalav
7   41.884250  -87.632450          Chicago, IL      BeingZhenya
8   32.715680 -117.161710        San Diego, CA        ohsillyjo
9   40.992070  -74.035980         Westwood, NJ      Anastasia71
10  40.992070  -74.035980         Westwood, NJ      Anastasia71
11  41.625050  -93.712430        Urbandale, IA        JennaKDay
12  41.313780  -81.504650        Macedonia, OH      Lizabelllaa
13  39.103440  -94.583110      Kansas City, MO    arthuradesign
14  41.884250  -87.632450          Chicago, IL    BrittanyJLadd
15  32.960740  -96.732970       Richardson, TX   loubiesandlulu
16  47.603570 -122.329450          Seattle, WA   DancesWithRain
17  41.884250  -87.632450          Chicago, IL            jpar0
18  41.698970  -71.462060          Warwick, RI           Kadamo
19  36.167840  -86.778160        Nashville, TN        carriedod
20  38.367983  -92.477747        Missouri, USA         CA_Young
21  39.103440  -94.583110      Kansas City, MO    arthuradesign
22  40.714000  -73.829990           Queens, NY         RMBouton
23  30.267590  -97.742990           Austin, TX      Steph_Demco
24  40.714500  -74.006010        Manhattan, NY    kellyFreckles
25   6.986130   80.813860         Editors Park         adinalav
26  37.512821  -78.697949        Virginia, USA     techybecky50
27  38.254890  -85.766660       Louisville, KY      nicolestipp
28  34.053490 -118.245320      Los Angeles, CA  MandiHefflinger
29  40.992070  -74.035980         Westwood, NJ      Anastasia71
..        ...         ...                  ...              ...
66  35.222860  -80.837960        Charlotte, NC          deboone
67  30.380320  -89.091890         Gulfport, MS  HealthNutsStore
68  25.726850  -80.355040  Olympia Heights, FL  Lyfestyle_Cater
69  40.714500  -74.006010        Manhattan, NY    kellyFreckles
70  27.946530  -82.459270            Tampa, FL     jingjingtaco
71  45.511790 -122.675630         Portland, OR        CrispNoPo
72  39.961990  -83.002750         Columbus, OH     OOHS_APYoung
73  36.755280  -76.059620   Virginia Beach, VA     kels_boyette
74  39.103440  -94.583110      Kansas City, MO    arthuradesign
75  37.777120 -122.419640    San Francisco, CA       JoshRotter
76  37.777120 -122.419640    San Francisco, CA       JoshRotter
77  47.603570 -122.329450          Seattle, WA       Maneesha_J
78  40.692450  -73.990360         Brooklyn, NY  caitlin_brimmer
79  44.943390  -93.096480          St Paul, MN       SHUTUPRUSH
80  40.692450  -73.990360         Brooklyn, NY         donachai
81  40.714500  -74.006010        Manhattan, NY        TheBGates
82  47.603570 -122.329450          Seattle, WA   DancesWithRain
83  40.714500  -74.006010        Manhattan, NY        kimmfoote
84  40.714500  -74.006010        Manhattan, NY        kimmfoote
85  32.778150  -96.795400           Dallas, TX   loubiesandlulu
86  52.215200    0.125540  Tommy Tucker Realty     Robin_Tucker
87  25.726850  -80.355040  Olympia Heights, FL  Lyfestyle_Cater
88  39.415740  -77.412030        Frederick, MD    dj_lizkhalifa
89  39.103440  -94.583110      Kansas City, MO    arthuradesign
90  39.103440  -94.583110      Kansas City, MO    arthuradesign
91  40.992070  -74.035980         Westwood, NJ      Anastasia71
92  40.992070  -74.035980         Westwood, NJ      Anastasia71
93  36.755280  -76.059620   Virginia Beach, VA     kels_boyette
94  47.603570 -122.329450          Seattle, WA          Dsummer
95  40.714500  -74.006010        Manhattan, NY        TheBGates

[96 rows x 4 columns]

In [4]:
# Drop NaN's
whole30_data_split_no_missing = whole30_location_df.dropna()
whole30_data_split_no_missing.head()

        lat        lng   tweet_location             user
0  41.19185 -111.96758  South Ogden, UT       mtheodoreb
1  39.96377  -75.59540      Mabel's BBQ  soverycleveland
2  40.69245  -73.99036     Brooklyn, NY     CatchGifUCan
3  39.92086 -105.07058   Broomfield, CO  rebekahljohnson
4  45.51179 -122.67563     Portland, OR      FoxandBones

In [5]:
# Create Open Columns
whole30_data_split_no_missing["state"] = ""
whole30_data_split_no_missing["city"] = ""
whole30_data_split_no_missing

# Split City & State
whole30_data_split_no_missing[["city", "state"]] = whole30_data_split_no_missing["tweet_location"].str.split(",", expand=True)
whole30_data_split_no_missing.head()

        lat        lng   tweet_location             user state         city
0  41.19185 -111.96758  South Ogden, UT       mtheodoreb    UT  South Ogden
1  39.96377  -75.59540      Mabel's BBQ  soverycleveland  None  Mabel's BBQ
2  40.69245  -73.99036     Brooklyn, NY     CatchGifUCan    NY     Brooklyn
3  39.92086 -105.07058   Broomfield, CO  rebekahljohnson    CO   Broomfield
4  45.51179 -122.67563     Portland, OR      FoxandBones    OR     Portland

In [6]:
# Groupby "state" & Get Mean (Average) Location from Each state
locations = whole30_data_split_no_missing.groupby("state").mean()
locations.head()

             lat         lng
state
 CA    35.571463 -120.054022
 CO    40.082913 -105.090340
 FL    26.281770  -80.881097
 GA    33.748310  -84.391110
 IA    41.607430  -93.663905

In [7]:
# Value Count Each "state" (Total Tweets per State) & Sort Index by Alphabetical Order to Align with Locations
location_counts = whole30_data_split_no_missing["state"].value_counts()
reorganized_location_count = location_counts.sort_index()
reorganized_location_count

 CA      6
 CO      3
 FL      4
 GA      4
 IA      2
 IL      7
 KY      1
 MD      1
 MI      1
 MN      1
 MO     11
 MS      1
 NC      1
 NJ      5
 NM      1
 NY     13
 OH      2
 OR      4
 RI      1
 SC      1
 TN      1
 TX      4
 USA     2
 UT      1
 VA      2
 WA     12
Name: state, dtype: int64

In [8]:
# Plot Heatmap
fig = gmaps.figure()

# Create Heat Layer
heat_layer = gmaps.heatmap_layer(locations, weights=reorganized_location_count, dissipating=False, max_intensity=10, point_radius=1)

# Add Layer 
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))